<?php

Route::get('/','pagecontroller@index');
Route::get('/table_creation','pagecontroller@table_creation');
Route::get('/insertion','pagecontroller@insertion');
Route::get('/modification','pagecontroller@modification');
Route::get('/update_delete','pagecontroller@update_delete');
Route::get('/query_and_aggregate','pagecontroller@query_and_aggregate');
Route::get('/join','pagecontroller@join');
Route::match(['get','post'],'/insert_user','pagecontroller@insert_user');
Route::match(['get','post'],'/insert_manager','pagecontroller@insert_manager');
Route::match(['get','post'],'/insert_access','pagecontroller@insert_access');
Route::match(['get','post'],'/insert_institution_type','pagecontroller@insert_institution_type');
Route::match(['get','post'],'/insert_department','pagecontroller@insert_department');
Route::match(['get','post'],'/insert_institution','pagecontroller@insert_institution');
Route::match(['get','post'],'/query_user','pagecontroller@query_user');
Route::match(['get','post'],'/query_manager','pagecontroller@query_manager');
Route::match(['get','post'],'/query_access','pagecontroller@query_access');
Route::match(['get','post'],'/query_institution','pagecontroller@query_institution');
Route::match(['get','post'],'/query_institution_user','pagecontroller@query_institution_user');
Route::match(['get','post'],'/query_count','pagecontroller@query_count');
Route::match(['get','post'],'/update_delete_user','pagecontroller@update_delete_user');
Route::match(['get','post'],'/update_delete_manager','pagecontroller@update_delete_manager');
Route::match(['get','post'],'/update_delete_access','pagecontroller@update_delete_access');
Route::match(['get','post'],'/update_delete_institution','pagecontroller@update_delete_institution');
Route::match(['get','post'],'/update_delete_department','pagecontroller@update_delete_department');
Route::match(['get','post'],'/update_delete_institution_type','pagecontroller@update_delete_institution_type');
